# Generated by Django 5.2.17 on 2026-09-08 09:46

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Coordinate GPS')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrizione/Note')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Posizione Segnalata')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Dettagli aggiuntivi')),
                ('media_url', models.URLField(max_length=500, verbose_name='URL Foto/Video Prova')),
                ('status', models.CharField(choices=[('PENDING', 'In attesa'), ('APPROVED', 'Approvato'), ('REJECTED', 'Rifiutato')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Note Admin (Motivo rifiuto)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utente Segnalatore')),
            ],
        ),
    ]
