# Generated by Django 5.2.17 on 2026-09-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingsubmission',
            name='media_url',
        ),
        migrations.AddField(
            model_name='parkingsubmission',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='submissions/', verbose_name='Foto Prova'),
        ),
    ]
