# Generated by Django 5.2.17 on 2026-09-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_remove_parkingsubmission_media_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='spots/', verbose_name='Foto Posteggio'),
        ),
    ]
